### ISSUE TITLE
HA Addon discontinued?

### ISSUE THREAD

**Issue by bggsolar** [muexxl/ha_addons#18]
Hi

I just wonder whether I've missed something or if there is no further development of the ha_Addon for batcontrol. 

Seems that linkage between the addon / docker hull and the main source of batcontrol are broken or is the current version still remaining at 1.5.0?

What have I missed so far?

Greets!

**Comment by muexxl** [comment]
Hi, 
you are right, curently it does not point to the most recent version. 
The reason is, that there has been no clean version management on the src repo. 
Currently we are working on a couple of features + release management. 
Once we fixed this in the src repo, I am going to link the ha addon to the latest version.

**Comment by muexxl** [comment]
Is there anything in particular that you need from a newer version ?

**Comment by bert500** [comment]
Hallo, vielen Dank für das Projekt.
Gibt es in HA einen Weg die einzelnen Modi aktivieren?
Oder das Lastprofil zu bearbeiten? 
Ist es evtl. möglich, die Entladeleistung in einem Zeitraum zu begrenzen? (Da ich nachts das EAuto lade) z.B. 0-7 Uhr, auf max. 3000W, sowie im Fronius Solarwebinterface.  

Vielen Dank und viele Grüße. Bert

**Comment by muexxl** [comment]
>>Gibt es in HA einen Weg die einzelnen Modi aktivieren?
Jein.. Wir arbeiten gerade an einer MQTT API. Darüber könnte das dann gehen. 
Grundsätzlich macht es auch keinen Sinn manuelle Modi zu setzen, so lange batcontrol aktiv ist, da ja spätestens beim nächsten Durchlauf, wieder der Modus gesetzt wird, den Batcontrol vorsieht. 

>> Oder das Lastprofil zu bearbeiten?
Wenn ich Zeit finde, baue ich eine Grafische Oberfläche. 
Bis dahin kannst du das Lastprofil bearbeiten indem du im Addon container direkt die Datei /batcontrol/config/load_profile.csv editierst / ersertzt 

>> Ist es evtl. möglich, die Entladeleistung in einem Zeitraum zu begrenzen? (Da ich nachts das EAuto lade) z.B. 0-7 Uhr, auf max. 3000W, sowie im Fronius Solarwebinterface.
Bisher ist das nicht möglich. Das sollte sich aber mit relativ geringem Aufwand implementieren lassen

**Comment by bggsolar** [comment]
> Is there anything in particular that you need from a newer version ?
> 
> 

Hi,
Well the only thing is, that connections to FC Solar seem to be broken. Some months ago I made some alterations to a fork version adding the possibility for fc api codes. 

Currently I receive errors regarding unavailability of fc solar within batcontrol. 

So unsure where to start now as I use the ha_addon. 

Cheers!

**Comment by muexxl** [comment]
I pushed the addon to the latest version. Please open an issue if the problem persists.
